Add a variant of thermodynamic FBA
LCSB-BioCore/COBREXA.jl pull request #437
Opened 2021-08-13 14:26 UTC by stelmo

Add a basic variant of thermodynamic FBA. Not the mixed interger approach, but rather the quadratically constrained implementation.

2021-08-13 14:28 UTC, cylon-x commented
:green_circle: &nbsp;Commit 8a770138 is formatted properly.

2021-08-13 20:24 UTC, stelmo commented
This is basically done, the only problem is that the function is nonlinear :/

2021-08-13 20:25 UTC, cylon-x commented
:green_circle: &nbsp;Commit 51c7e8b6 is formatted properly.

2021-08-13 20:31 UTC, cylon-x commented
:green_circle: &nbsp;Commit b06be994 is formatted properly.

2021-08-30 19:36 UTC, cylon-x commented
:green_circle: &nbsp;Commit 25646753 is formatted properly.

2021-08-30 20:37 UTC, cylon-x commented
:green_circle: &nbsp;Commit 606a203a is formatted properly.

2021-11-02 12:09 UTC, cylon-x commented
:red_square: &nbsp;Commit 02979d87 requires formatting!

Required formatting changes summary:
```
 src/base/utils/Reaction.jl | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)
```

2021-11-02 12:09 UTC, cylon-x commented
:red_square: &nbsp;Commit 02979d87 requires formatting!

Required formatting changes summary:
```
 src/base/utils/Reaction.jl | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)
```

2021-11-02 12:46 UTC, cylon-x commented
:red_square: &nbsp;Commit 1e9461a1 requires formatting!

Required formatting changes summary:
```
 test/analysis/fba_with_crowding.jl | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
```

2021-11-02 12:58 UTC, cylon-x commented
:green_circle: &nbsp;Commit 2195a017 is formatted properly.

2021-11-02 13:04 UTC, cylon-x commented
:green_circle: &nbsp;Commit 06a40266 is formatted properly.

2021-11-02 13:14 UTC, cylon-x commented
:green_circle: &nbsp;Commit 56424af7 is formatted properly.

2021-11-02 14:52 UTC, cylon-x commented
:green_circle: &nbsp;Commit c2f6a4de is formatted properly.

2021-11-02 15:16 UTC, cylon-x commented
:green_circle: &nbsp;Commit c4845e4b is formatted properly.

2021-11-02 20:02 UTC, exaexa requested changes
Tiny changes required, otherwise looks OK, well balanced add/remove line ratio :D

2021-11-02 20:02 UTC, exaexa commented on src/base/constants.jl
> +    strict_inequality_tolerance = 1,
naming: perhaps add something about what purpose this serves, like "loopless_inequality_tolerance" or "slack_variable_bound_tolerance" or something?

2021-11-02 20:02 UTC, exaexa commented on test/analysis/fba_with_crowding.jl
> -    idxs = find_internal_reactions(model)
semantic shift very welcome

2021-11-02 20:33 UTC, cylon-x commented
:green_circle: &nbsp;Commit b79b8516 is formatted properly.

2021-11-02 20:38 UTC, cylon-x commented
:green_circle: &nbsp;Commit 5edca7f7 is formatted properly.

2021-11-02 21:00 UTC, cylon-x commented
:green_circle: &nbsp;Commit 29769c75 is formatted properly.

2021-11-02 21:10 UTC, stelmo commented
I squashed into two commits: one for the NLP stuff that didn't work (to be continued :]) and the actual implemented one: loopless.

2021-11-02 21:18 UTC, exaexa approved these changes

2021-11-02 21:25 UTC, merged